/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Telas;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.white;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public TelaLogin() {
        initComponents();
        configurarJanela();
        configuraLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarJanela() {
        // Configurações extras da janela
        setTitle("Login - Sistema de Adoção");
        setSize(800, 500);
        setResizable(true); // previne mudança de tamanho da tela
        setLocationRelativeTo(null); // centraliza a tela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color (189, 206, 211));
        //pack();
    }
    
    
    private void configuraLabel(){
        // cria paineis
        getContentPane().setLayout(null);
        setLayout(new BorderLayout());
        JPanel norte = new JPanel();
        norte.setPreferredSize(new Dimension(100,100));
        norte.setBackground(new Color (189, 206, 211));
         
        JPanel centro = new JPanel();
        centro.setBackground(new Color (189, 206, 211));
        centro.setPreferredSize(new Dimension(100,100));
        centro.setLayout(null);// permite usar setBounds
        
        JPanel sul = new JPanel();
        sul.setPreferredSize(new Dimension(100,100));
        sul.setBackground(new Color (189, 206, 211));
        
        JPanel leste = new JPanel();
        leste.setPreferredSize(new Dimension(150,150));
        leste.setBackground(new Color (189, 206, 211));
        
        JPanel oeste= new JPanel();
        oeste.setPreferredSize(new Dimension(150,150));
        oeste.setBackground(new Color (189, 206, 211));
      
       
       getContentPane().add(norte,BorderLayout.NORTH);
       getContentPane().add(centro,BorderLayout.CENTER);
       getContentPane().add(sul,BorderLayout.SOUTH);
       getContentPane().add(leste,BorderLayout.EAST);
       getContentPane().add(oeste,BorderLayout.WEST);
       
       
       //CRIA LABEL E TEXTFIELD
       //getContentPane().setLayout(null);
        JLabel labelEmail = new JLabel();
        labelEmail.setText("Email:"); // texto da label
        labelEmail.setBounds(50, 50, 100, 25); // x, y, width, height
        labelEmail.setForeground(Color.BLACK); // define cor do texto
        labelEmail.setFont(new Font ("INTER", Font.PLAIN,20));
        // Cria campo de texto
        JTextField campoEmail = new JTextField();
        campoEmail.setBounds(50, 80, 400, 25);
        // Adiciona componentes
        centro.add(labelEmail);
        centro.add(campoEmail);

        // cria label e campo de texto para senha
        JLabel labelSenha = new JLabel("Senha:");
        labelSenha.setBounds(50, 120, 100, 25);
        labelSenha.setForeground(Color.BLACK);
        labelSenha.setFont(new Font ("INTER", Font.PLAIN,20));
        JPasswordField campoSenha = new JPasswordField();
        campoSenha.setBounds(50, 140, 400, 25);
        centro.add(labelSenha);
        centro.add(campoSenha);
        
        // configura botao de login 
        JButton btnLogin = new JButton("Login");
        btnLogin.setBounds(380, 180, 90, 50);
        btnLogin.setVisible(true);
        btnLogin.setFont(new Font ("INTER", Font.BOLD,15));
        centro.add(btnLogin);
        
       
        
        // Atualiza a tela
        revalidate();
        repaint();

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
