/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Telas;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextField;
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public TelaLogin() {
        initComponents();
        configurarJanela();
        configuraLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarJanela() {
        // Configurações extras da janela
        setTitle("Login - Sistema de Adoção");
        setSize(800, 500);
        setResizable(true); // previne mudança de tamanho da tela
        setLocationRelativeTo(null); // centraliza a tela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(new Color (189, 206, 211));
        //pack();
    }
    
    private void configuraLabel(){
        getContentPane().setLayout(null);
        JLabel labelEmail = new JLabel();
        labelEmail.setText("Email:"); // texto da label
        labelEmail.setBounds(50, 50, 100, 25); // x, y, width, height
        labelEmail.setForeground(Color.BLACK); // define cor do texto
        labelEmail.setFont(new Font ("INTER", Font.PLAIN,20));
        // Cria campo de texto
        JTextField campoEmail = new JTextField();
        campoEmail.setBounds(50, 80, 400, 25);
        // Adiciona componentes
        getContentPane().add(labelEmail);
        getContentPane().add(campoEmail);

        // cria label e campo de texto para senha
        JLabel labelSenha = new JLabel("Senha:");
        labelSenha.setBounds(50, 120, 100, 25);
        labelSenha.setForeground(Color.BLACK);
        labelSenha.setFont(new Font ("INTER", Font.PLAIN,20));
        JTextField campoSenha = new JTextField();
        campoSenha.setBounds(50, 140, 400, 25);
        getContentPane().add(labelSenha);
        getContentPane().add(campoSenha);
        // Atualiza a tela
        revalidate();
        repaint();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
